name: Build and Push Docker Images

on:
  push:
    tags:
      - 'v*'  # build only for tags

jobs:
  build:
    name: Build and Push Multi-Arch Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        service: [
          {name: 'paperless-export-api', dockerfile: 'Dockerfile'},
          {name: 'paperless-export-mcp-server-sse', dockerfile: 'Dockerfile.McpServer.SSE'},
          {name: 'paperless-export-mcp-server', dockerfile: 'Dockerfile.McpServer'},
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.service.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            mctristan/${{ matrix.service.name }}:latest
            mctristan/${{ matrix.service.name }}:${{ env.VERSION }}
